name: Frontend Asset Sizes

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: simplabs/ember-asset-size-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        working-directory: packages/frontend

